# Generated by Django 5.1.7 on 2025-04-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100)),
                ("translation", models.CharField(max_length=100)),
                ("example", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("noun", "Noun"),
                            ("verb", "Verb"),
                            ("adjective", "Adjective"),
                            ("adverb", "Adverb"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
